name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Cargo build and test
      id: cargo_build_and_test
      run: |
        cargo fmt -- --check
        cargo build --release --verbose
        cargo test --verbose
        cargo run --example gallery
        cargo run --example inspect
        cargo run --example walk
        cargo install --path shader-reflect
        shader-reflect assets/gallery.frag -o assets/gallery.frag.json --reference-all-resources
        shader-reflect assets/gallery.frag.spv -o assets/gallery.frag.spv.json --reference-all-resources
        diff assets/gallery.frag.json assets/gallery.frag.spv.json
        shader-reflect assets/spirv-spec.frag -o assets/spirv-spec.frag.json
        shader-reflect assets/spirv-spec.frag.spv -o assets/spirv-spec.frag.spv.json
        diff assets/spirv-spec.frag.json assets/spirv-spec.frag.spv.json
        git diff --exit-code
